Repository orca-services/netvibes-replacement, pull requests merged in 2025-04, with the labels that each got.

#7 #6 Added a Changelog
  CHANGELOG.md
Labels: documentation

#9 Implement authentication with registration, login and logout through cakedc/users plugin #4 #5
  .idea/netvibes-replacement.iml
  .idea/php.xml
  CHANGELOG.md
  composer.json
  composer.lock
  config/Migrations/20250423124957_AddUsersRelatedTables.php
  config/Migrations/schema-dump-default.lock
  config/permissions.php
  config/users.php
  src/Application.php
Labels: authentication

#10 #3 Add Start page
  CHANGELOG.md
  config/permissions.php
  config/routes.php
  src/Controller/StartController.php
  templates/Pages/home.php
  templates/Start/start.php
Labels: enhancement

#12 #11 Add Dashboard CRUD
  CHANGELOG.md
  config/Migrations/20250424114924_ChangeUserIdToInteger.php
  config/Migrations/20250424131321_AddDashboardsTable.php
  config/Migrations/schema-dump-default.lock
  config/permissions.php
  src/Controller/DashboardsController.php
  src/Model/Entity/.gitkeep
  src/Model/Entity/Dashboard.php
  src/Model/Table/.gitkeep
  src/Model/Table/DashboardsTable.php
  templates/Dashboards/add.php
  templates/Dashboards/edit.php
  templates/Dashboards/index.php
  templates/Dashboards/view.php
  tests/Fixture/.gitkeep
  tests/Fixture/DashboardsFixture.php
  tests/Fixture/UsersFixture.php
  tests/TestCase/Controller/DashboardsControllerTest.php
  tests/TestCase/Controller/PagesControllerTest.php
  tests/TestCase/Model/Table/DashboardsTableTest.php
Labels: enhancement
